export const contacts = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.j@techcorp.com',
    company: 'TechCorp Inc.',
    phone: '+1 (555) 123-4567',
    position: 'CTO',
    status: 'active',
    avatar: 'SJ',
    lastContact: '2025-11-20',
    value: 125000,
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'm.chen@innovate.io',
    company: 'Innovate Solutions',
    phone: '+1 (555) 234-5678',
    position: 'CEO',
    status: 'active',
    avatar: 'MC',
    lastContact: '2025-11-21',
    value: 250000,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@startupxyz.com',
    company: 'StartupXYZ',
    phone: '+1 (555) 345-6789',
    position: 'Founder',
    status: 'lead',
    avatar: 'ER',
    lastContact: '2025-11-19',
    value: 75000,
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'j.wilson@enterprise.com',
    company: 'Enterprise Corp',
    phone: '+1 (555) 456-7890',
    position: 'VP Sales',
    status: 'active',
    avatar: 'JW',
    lastContact: '2025-11-22',
    value: 180000,
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'l.anderson@growth.co',
    company: 'Growth Partners',
    phone: '+1 (555) 567-8901',
    position: 'Director',
    status: 'lead',
    avatar: 'LA',
    lastContact: '2025-11-18',
    value: 95000,
  },
]

export const deals = [
  {
    id: '1',
    title: 'Enterprise Software License',
    company: 'TechCorp Inc.',
    value: 125000,
    stage: 'negotiation',
    probability: 75,
    closingDate: '2025-12-15',
    contact: 'Sarah Johnson',
  },
  {
    id: '2',
    title: 'Cloud Infrastructure Migration',
    company: 'Innovate Solutions',
    value: 250000,
    stage: 'proposal',
    probability: 60,
    closingDate: '2025-12-30',
    contact: 'Michael Chen',
  },
  {
    id: '3',
    title: 'Custom Development Project',
    company: 'StartupXYZ',
    value: 75000,
    stage: 'discovery',
    probability: 40,
    closingDate: '2026-01-20',
    contact: 'Emily Rodriguez',
  },
  {
    id: '4',
    title: 'Annual Support Contract',
    company: 'Enterprise Corp',
    value: 180000,
    stage: 'closed-won',
    probability: 100,
    closingDate: '2025-11-15',
    contact: 'James Wilson',
  },
]

export const tasks = [
  {
    id: '1',
    title: 'Follow up with TechCorp about contract',
    description: 'Send updated proposal with revised pricing',
    dueDate: '2025-11-23',
    priority: 'high',
    status: 'todo',
    assignedTo: 'You',
    relatedTo: 'Sarah Johnson - TechCorp Inc.',
  },
  {
    id: '2',
    title: 'Schedule demo for Innovate Solutions',
    description: 'Prepare cloud migration presentation',
    dueDate: '2025-11-24',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'You',
    relatedTo: 'Michael Chen - Innovate Solutions',
  },
  {
    id: '3',
    title: 'Research StartupXYZ requirements',
    description: 'Gather technical specifications for custom dev',
    dueDate: '2025-11-25',
    priority: 'medium',
    status: 'todo',
    assignedTo: 'Team',
    relatedTo: 'Emily Rodriguez - StartupXYZ',
  },
  {
    id: '4',
    title: 'Send thank you note to Enterprise Corp',
    description: 'Acknowledge contract signing',
    dueDate: '2025-11-22',
    priority: 'low',
    status: 'completed',
    assignedTo: 'You',
    relatedTo: 'James Wilson - Enterprise Corp',
  },
]

export const activities = [
  {
    id: '1',
    type: 'email',
    title: 'Email sent to Sarah Johnson',
    description: 'Proposal for Enterprise Software License',
    timestamp: '2025-11-22T10:30:00',
    contact: 'Sarah Johnson',
  },
  {
    id: '2',
    type: 'call',
    title: 'Call with Michael Chen',
    description: 'Discussed cloud migration timeline',
    timestamp: '2025-11-22T09:15:00',
    contact: 'Michael Chen',
  },
  {
    id: '3',
    type: 'meeting',
    title: 'Meeting with Lisa Anderson',
    description: 'Initial discovery meeting',
    timestamp: '2025-11-21T14:00:00',
    contact: 'Lisa Anderson',
  },
  {
    id: '4',
    type: 'note',
    title: 'Note added for Emily Rodriguez',
    description: 'Requested detailed technical requirements',
    timestamp: '2025-11-21T11:45:00',
    contact: 'Emily Rodriguez',
  },
]

export const metrics = [
  {
    label: 'Total Revenue',
    value: '$725K',
    change: '+12.5%',
    trend: 'up' as const,
  },
  {
    label: 'Active Deals',
    value: '12',
    change: '+3',
    trend: 'up' as const,
  },
  {
    label: 'Win Rate',
    value: '68%',
    change: '+5.2%',
    trend: 'up' as const,
  },
  {
    label: 'Avg Deal Size',
    value: '$157K',
    change: '-2.1%',
    trend: 'down' as const,
  },
]

export const revenueData = [
  { month: 'Jan', revenue: 45000 },
  { month: 'Feb', revenue: 52000 },
  { month: 'Mar', revenue: 48000 },
  { month: 'Apr', revenue: 61000 },
  { month: 'May', revenue: 55000 },
  { month: 'Jun', revenue: 67000 },
  { month: 'Jul', revenue: 72000 },
  { month: 'Aug', revenue: 68000 },
  { month: 'Sep', revenue: 75000 },
  { month: 'Oct', revenue: 82000 },
  { month: 'Nov', revenue: 725000 / 11 }, // Current month
]

export const pipelineData = [
  { stage: 'Discovery', value: 285000, count: 8 },
  { stage: 'Proposal', value: 425000, count: 5 },
  { stage: 'Negotiation', value: 315000, count: 3 },
  { stage: 'Closed Won', value: 725000, count: 12 },
]
